stages:
  - build
  - deploy

# Fully build and publish master branch
build_and_publish:
  type: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -U -B clean test -DskipDockerBuild -DskipDockerTag
  except:
    - master

deploy_docs:
  type: deploy
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - mvn -q -B clean package -pl :docs
    - scp -o 'StrictHostKeyChecking no' -B -r docs/target/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master