image: java:8

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e test@example.com docker.cern.ch

build:
  script:
   - ./mvnw -q -B -T4 -U clean deploy --settings settings.xml
