stages:
  - precompile
  - compile
  - test
  - qa
  - publish
  - deploy

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn $MAVEN_CLI_OPTS/maven.config` so the same config is used
  # when running from the command line.
  MAVEN_CLI_OPTS:
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --threads 4.0C
      --batch-mode --errors --fail-at-end --show-version --settings $CI_PROJECT_DIR/settings.xml
# It would be good to get the certs for this one

#  =========================
#  === Stage: Precompile ===
#  =========================

.build_base:
  stage: compile
  dependencies: []
#  tags: [c2mon]
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - .m2/
      - .mvn
  script:
    - export MAVEN_OPTS=""
    - mvnw dependency:go-offline
    - cd $TARGET
    - ../mvnw $MAVEN_CLI_OPTS test-compile
  artifacts:
    name: "$TARGET#$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 60 minutes
  except:
    - master
    - tags

build_shared:
  extends: .build_base
  stage: precompile
  cache:
    policy: pull-push
#  script:
#    - export MAVEN_OPTS=""
#  https://issues.apache.org/jira/browse/MDEP-82
#    - ./mvnw $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true org.apache.maven.plugins:maven-dependency-plugin:3.0.0:go-offline
#    - cd c2mon-shared
#    - ../mvnw $MAVEN_CLI_OPTS -o test-compile
  variables:
    TARGET: "c2mon-shared"
  artifacts:
    paths:
      - c2mon-shared

#  =========================
#  ===== Stage: Compile ====
#  =========================

build_docs:
  stage: compile
  tags: [docker]
  image: jekyll/builder:3.8.5
  script:
    - cd docs
    - jekyll build --config "_config.yml,_overwrite_url.yml"
  artifacts:
    name: site
    when: on_success
    expire_in: 7 days
    paths:
      - _site
  only:
    - master

build_server:
  extends: .build_base
  dependencies: [build_shared]
  variables:
    TARGET: "c2mon-server"
  artifacts:
    paths: [c2mon-server]

build_client:
  extends: .build_base
  dependencies: [build_shared]
  variables:
    TARGET: "c2mon-client"
  artifacts:
    paths: [c2mon-client]

build_daq:
  extends: .build_base
  dependencies: [build_shared]
  variables:
    TARGET: "c2mon-daq"
  artifacts:
    paths: [c2mon-daq]

#  =========================
#  ===== Stage: Test =======
#  =========================

.test_base:
  stage: test
#  tags: [c2mon]
  script:
    - export MAVEN_OPTS=""
    - mkdir reports
    - cd $TARGET
    - ../mvnw $MAVEN_CLI_OPTS test && find -iname 'TEST-*.xml' -exec cp {} ../reports/ \;
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 60 minutes
    when: on_success
    reports:
      junit: reports/*.xml
  except:
    - master
    - tags

# Ordered higher as it's the slowest to run
test_server:
  extends: .test_base
  dependencies:
    - build_shared
    - build_server
  variables:
    TARGET: "c2mon-server"

test_shared:
  extends: .test_base
  dependencies:
    - build_shared
  variables:
    TARGET: "c2mon-shared"

test_client:
  extends: .test_base
  dependencies:
    - build_shared
    - build_client
  variables:
    TARGET: "c2mon-client"

test_daq:
  extends: .test_base
  dependencies:
    - build_shared
    - build_daq
  variables:
    TARGET: "c2mon-daq"

#  =========================
#  ====== Stage: QA ========
#  =========================

sonar_preview:
  stage: qa
  tags: [c2mon]
  dependencies:
    - build_shared
    - build_server
    - build_client
    - build_daq
  script:
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0
  except:
    - master
    - tags

quality_assurance:
  stage: qa
  tags: [c2mon]
  dependencies:
    - build_shared
    - build_server
    - build_client
    - build_daq
  script:
    - mvn $MAVEN_CLI_OPTS package sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
  only:
    - master

#  =========================
#  ===== Stage: Publish ====
#  =========================

# Fully build and publish master branch
publish:
  stage: publish
  tags: [c2mon]
  dependencies:
    - build_shared
    - build_server
    - build_client
    - build_daq
  script:
    - mvn $MAVEN_CLI_OPTS -P ci-deploy deploy
  only:
    - master

# Publish docker images?

#  =========================
#  ===== Stage: Deploy =====
#  =========================

trigger_build:
  stage: deploy
  tags: [c2mon]
  dependencies: []
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  stage: deploy
  tags: [no-runner-9]
  dependencies:
    - build_docs
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - scp -o 'StrictHostKeyChecking no' -o 'GSSAPITrustDNS yes' -o 'GSSAPIDelegateCredentials yes' -B -r docs/_site/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master