image: docker:latest

services:
- docker:dind # https://cdn.meme.am/instances/500x/49519932.jpg

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.cern.ch

build:
  script:
   - ./mvnw -q -B -T4 -U clean deploy --settings settings.xml
