stages:
  - build
  - deploy

# Fully build and publish master branch
build_and_publish:
  type: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -U -B clean test -DskipDockerBuild -DskipDockerTag --settings settings.xml -Ddependencies.set.direct
  except:
    - master

deploy_docs:
  type: deploy
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - mvn -q -B clean package -pl :docs
    - scp -o 'StrictHostKeyChecking no' -B -r docs/target/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master

# CERN-specific triggers.
trigger:
  type: deploy
  script:
    # Trigger build of tim-server
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9859/trigger/builds"
  only:
    - master