stages:
  - cache

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  MAVEN_CLI_OPTS:
    --errors --fail-at-end

# Will be used by other branches
cache:
  key: "base"
  policy: pull-push
  paths:
    - .m2

image:
  name: maven:3.6.2-jdk-11-slim

# Preloads the local repository with cached dependencies
build_cache:
  stage: cache
  script:
    # This variable is being set at the TIM level and can affect our builds
    - export MAVEN_OPTS=""
    - apt-get update && apt-get install git -y -q
    # We wish to build cache for master - this branch WILL fall behind
    - git checkout master
    # Nuke existing repo
    - rm -rf .m2 node
    - ./mvnw $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true package -Dmaven.wagon.http.ssl.allowall=true org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline