stages:
  - clean
  - compile
  - test
  - deploy
  - sonar


#  =========================
#  ===== Stage: Clean ======
#  =========================

clean_elasticsearch:
  stage: clean
  tags: [c2mon]
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - killall -q java || true
    - rm -Rf /tmp/es-cluster*

#  =========================
#  ===== Stage: Compile ====
#  =========================

# Fully build and publish master branch
.build_and_publish:
  stage: compile
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct
  only:
    - master

# Just run tests on feature branches
.build:
  stage: compile
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean test -DskipDocker=true --settings settings.xml -Ddependencies.set.direct --debug -X
  except:
    - master
    - tags

build_docs:
  stage: compile
  tags: [docker]
  image: jekyll/builder:3.8.5
  script:
    - cd docs
    - jekyll build --config "_config.yml,_overwrite_url.yml"
  artifacts:
    name: site
    when: on_success
    expire_in: 7 days
    untracked: true
    paths:
      - _site
  only:
    - master

.build_base:
  stage: compile
  tags: [c2mon]
  dependencies: []
  artifacts:
    when: on_success
    expire_in: 120 minutes
    untracked: true
  except:
    - master
    - tags

build_shared:
  extends: .build_base
  script:
    - cd c2mon-shared
    - mvn -U -B test-compile
  artifacts:
    name: "c2mon-shared#$CI_COMMIT_REF_NAME"
    paths: [c2mon-shared]

build_server:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-server
    - mvn -U -B test-compile
  artifacts:
    name: "c2mon-server#$CI_COMMIT_REF_NAME"
    paths: [c2mon-server]

build_client:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-client
    - mvn -U -B test-compile
  artifacts:
    name: "c2mon-client#$CI_COMMIT_REF_NAME"
    paths: [c2mon-client]

build_daq:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-daq
    - mvn -U -B test-compile
  artifacts:
    name: "c2mon-daq#$CI_COMMIT_REF_NAME"
    paths: [c2mon-daq]

#  =========================
#  ===== Stage: Test =======
#  =========================

.test_base:
  stage: test
  tags: [c2mon]
  except:
    - master
    - tags

test_shared:
  extends: .test_base
  dependencies:
    - build_shared
  script:
    - cd c2mon-shared
    - mvn -U -B -X --debug test

test_server:
  extends: .test_base
  dependencies:
    - build_shared
    - build_server
  script:
    - cd c2mon-server
    - mvn -U -B -X --debug test

test_client:
  extends: .test_base
  dependencies:
    - build_shared
    - build_client
  script:
    - cd c2mon-client
    - mvn -U -B -X --debug test

test_daq:
  extends: .test_base
  dependencies:
    - build_shared
    - build_daq
  script:
    - cd c2mon-daq
    - mvn -U -B -X --debug test


#  =========================
#  ===== Stage: Deploy =====
#  =========================


trigger_build:
  stage: deploy
  tags: [c2mon]
  dependencies: []
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  stage: deploy
  tags: [no-runner-9]
  dependencies:
    - build_docs
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - scp -o 'StrictHostKeyChecking no' -o 'GSSAPITrustDNS yes' -o 'GSSAPIDelegateCredentials yes' -B -r docs/_site/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master

sonar_preview:
  stage: sonar
  tags: [c2mon]
  dependencies: []
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  tags: [c2mon]
  dependencies: []
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
