stages:
  - clean
  - build
  - deploy
  - sonar

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  
  
clean_elasticsearch:
  stage: clean
  variables:
    GIT_STRATEGY: none
  script:
    - killall -q java || true
    - rm -Rf /tmp/es-cluster*

# Fully build and publish master branch
build_and_publish:
  stage: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml -Ddependencies.set.direct
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  tags: 
    - docker-privileged
  image: gitlab-registry.cern.ch/industrial-controls/sw-infra/mvn-dind:baseline
  services:    
    - docker:19.03.0-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - mvn -q -U -B clean test -DskipDocker=true --settings settings.xml -Ddependencies.set.direct --debug -X
  except:
    - master
    - tags

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  stage: deploy
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - mvn -q -B clean package -pl :docs
    - scp -o 'StrictHostKeyChecking no' -B -r docs/target/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master

sonar_preview:
  stage: sonar
  image: gitlab-registry.cern.ch/industrial-controls/sw-infra/mvn-dind:baseline
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
