stages:
  - cache

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  MAVEN_CLI_OPTS:
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    --batch-mode --errors --fail-at-end --show-version --settings $CI_PROJECT_DIR/settings.xml

# Will be used by other branches
cache:
  key: "base"
  policy: pull-push
  paths:
    - .m2

image:
  name: gitlab-registry.cern.ch/industrial-controls/sw-infra/cc7-maven:git-jdk-11-mvn-3.6-1
  entrypoint: [""]

# Preloads the local repository with cached dependencies
build_cache:
  stage: cache
  script:
    # This variable is being set at the TIM level and can affect our builds
    - export MAVEN_OPTS=""
#    - apt-get update && apt-get install git -y -q
    # We wish to build cache for master - this branch WILL fall behind
    - echo "Starting cache refresh" 
    - pwd
    - ls
    - git checkout issue-39
    # Nuke existing repol
    - rm -rf .m2 node
    - mvn $MAVEN_CLI_OPTS  -Dmaven.wagon.http.ssl.insecure=true -DskipTests package -Dmaven.wagon.http.ssl.allowall=true org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline