stages:
  - build
  - deploy

# Fully build and deploy master branch
build_and_deploy:
  type: build
  script:
    - mvn -q -U -B clean deploy --settings settings.xml
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -U -B clean test -DskipDockerBuild -DskipDockerTag
  except:
    - master

deploy_docs:
  type: deploy
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - mvn -q -B clean package -pl :docs
    - scp -B -r docs/target/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master

# CERN-specific triggers. Should be removed one day.
trigger:
  type: deploy
  script:
    # Trigger build of tim-server
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9859/trigger/builds"
    # Trigger build of c2mon-daq-alarmsource
    - "curl -X POST -F token=$C2MON_DAQ_ALARMSOURCE_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9143/trigger/builds"
    # Trigger build of c2mon-daq-db
    - "curl -X POST -F token=$C2MON_DAQ_DB_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9147/trigger/builds"
    # Trigger build of c2mon-daq-dip
    - "curl -X POST -F token=$C2MON_DAQ_DIP_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9148/trigger/builds"
    # Trigger build of c2mon-daq-japc
    - "curl -X POST -F token=$C2MON_DAQ_JAPC_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9149/trigger/builds"
    # Trigger build of c2mon-daq-jec
    - "curl -X POST -F token=$C2MON_DAQ_JEC_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9150/trigger/builds"
    # Trigger build of c2mon-daq-opcua
    - "curl -X POST -F token=$C2MON_DAQ_OPCUA_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9153/trigger/builds"
    # Trigger build of c2mon-client-ext-history
    - "curl -X POST -F token=$C2MON_CLIENT_EXT_HISTORY_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9115/trigger/builds"
  only:
    - master
