stages:
  - precompile
  - compile
  - test
  - qa
  - publish
  - deploy

#  =========================
#  === Stage: Precompile ===
#  =========================

.build_base:
  stage: compile
  dependencies: []
  artifacts:
    when: on_success
    expire_in: 120 minutes
    untracked: true
  except:
    - master
    - tags

build_shared:
  extends: .build_base
  stage: precompile
  script:
    - cd c2mon-shared
    - mvn -U -B test-compile --settings ../settings.xml
  artifacts:
    name: "c2mon-shared#$CI_COMMIT_REF_NAME"
    paths: [c2mon-shared]

#  =========================
#  ===== Stage: Compile ====
#  =========================

build_docs:
  stage: compile
  tags: [docker]
  image: jekyll/builder:3.8.5
  script:
    - cd docs
    - jekyll build --config "_config.yml,_overwrite_url.yml"
  artifacts:
    name: site
    when: on_success
    expire_in: 7 days
    untracked: true
    paths:
      - _site
  only:
    - master

build_server:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-server
    - mvn -q -U -B test-compile -pl '!distribution' --settings ../settings.xml
  artifacts:
    name: "c2mon-server#$CI_COMMIT_REF_NAME"
    paths: [c2mon-server]

build_client:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-client
    - mvn -q -U -B test-compile --settings ../settings.xml
  artifacts:
    name: "c2mon-client#$CI_COMMIT_REF_NAME"
    paths: [c2mon-client]

build_daq:
  extends: .build_base
  dependencies: [build_shared]
  script:
    - cd c2mon-daq
    - mvn -q -U -B test-compile --settings ../settings.xml
  artifacts:
    name: "c2mon-daq#$CI_COMMIT_REF_NAME"
    paths: [c2mon-daq]

#  =========================
#  ===== Stage: Test =======
#  =========================

.test_base:
  stage: test
  except:
    - master
    - tags

test_shared:
  extends: .test_base
  dependencies:
    - build_shared
  script:
    - cd c2mon-shared
    - mvn -U -B -X --debug test

test_server:
  extends: .test_base
  dependencies:
    - build_shared
    - build_server
  script:
    - cd c2mon-server
    - mvn -U -B -X --debug test

test_client:
  extends: .test_base
  dependencies:
    - build_shared
    - build_client
  script:
    - cd c2mon-client
    - mvn -U -B -X --debug test

test_daq:
  extends: .test_base
  dependencies:
    - build_shared
    - build_daq
  script:
    - cd c2mon-daq
    - mvn -U -B -X --debug test

#  =========================
#  ====== Stage: QA ========
#  =========================

sonar_preview:
  stage: qa
  dependencies:
    - build_shared
    - build_server
    - build_client
    - build_daq
  script:
    - mvn -q -U -B sonar:sonar -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: qa
  dependencies: []
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -DskipDocker=true -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master

#  =========================
#  ===== Stage: Publish ====
#  =========================

# Fully build and publish master branch
publish:
  stage: publish
  dependencies:
    - build_shared
    - build_server
    - build_client
    - build_daq
  script:
    - mvn -q -U -B deploy --settings settings.xml
  only:
    - master

# Publish docker images?

#  =========================
#  ===== Stage: Deploy =====
#  =========================

trigger_build:
  stage: deploy
  tags: [c2mon]
  dependencies: []
  script:
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/9859/trigger/pipeline"
  only:
  - master

deploy_docs:
  stage: deploy
  tags: [no-runner-9]
  dependencies:
    - build_docs
  script:
    - echo ${KRB_PASSWORD} | kinit ${KRB_USERNAME}@CERN.CH
    - scp -o 'StrictHostKeyChecking no' -o 'GSSAPITrustDNS yes' -o 'GSSAPIDelegateCredentials yes' -B -r docs/_site/* ${KRB_USERNAME}@lxplus:/afs/cern.ch/user/c/${KRB_USERNAME}/www/c2mon.web.cern.ch/docs
  only:
    - master