stages:
  - build
  - deploy

# Fully build and deploy master branch
build_and_deploy:
  type: build
  script:
    - mvn -q -B clean deploy --settings settings.xml
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -B test -DskipDockerBuild -DskipDockerTag
  except:
    - master

##
# CERN specific part. Should be removed one day
##

# Triggers the build of tim-server
trigger:
  type: deploy
  script:
    - "curl -X POST -F token=TIM_SERVER_TOKEN -F ref=REF_NAME https://gitlab.cern.ch/api/v3/projects/9859/trigger/builds"
  only:
    - master