stages:
  - build
  - deploy

# Fully build and deploy master branch
build_and_deploy:
  type: build
  script:
    - mvn -q -B clean deploy --settings settings.xml
  only:
    - master

# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -q -B test -DskipDockerBuild -DskipDockerTag
  except:
    - master

deploy_docs:
  type: deploy
  script:
    - cp -r docs/target/ ${DOCS_DEPLOY_DIR}
#  only:
#    - master

##
# CERN specific part. Should be removed one day
##

trigger:
  type: deploy
  script:
    # Trigger build of tim-server
    - "curl -X POST -F token=$TIM_SERVER_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9859/trigger/builds"
    # Trigger build of c2mon-daq-alarmsource
    - "curl -X POST -F token=$C2MON_DAQ_ALARMSOURCE_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9143/trigger/builds"
    # Trigger build of c2mon-daq-opcua
    - "curl -X POST -F token=$C2MON_DAQ_OPCUA_TOKEN -F ref=master https://gitlab.cern.ch/api/v3/projects/9153/trigger/builds"
  only:
    - master
