version: "3.0"
services:
   db:
     build: mysql/
     image: cernoss/c2mon-mysql
     ports:
       - "3306"
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     networks:
       - backend
   mq:
     image: webcenter/activemq:5.14.3
     ports:
       - "61616"
       - "61614"
     networks:
       - backend
   es:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
     environment:
       - cluster.name=c2mon
       - discovery.type=single-node
       - xpack.security.enabled=false
       - bootstrap.memory_lock=true # Disable swapping
       - TAKE_FILE_OWNERSHIP=1 # Ensure correct permission settings for user for volume
       - ES_JAVA_OPTS=-Xms512m -Xmx512m
     ulimits:
      memlock:
        soft: -1  # Limit heap size
        hard: -1
     ports:
       - "9200"
       - "9300"
     networks:
       - backend
   c2mon:
     image: gitlab-registry.cern.ch/c2mon/c2mon:1.8.38
     depends_on: 
       - db
       - mq
       - es
     environment:
      - C2MON_SERVER_JMS_EMBEDDED=false
      - C2MON_SERVER_JMS_URL=tcp://mq:61616
      - C2MON_SERVER_ELASTICSEARCH_EMBEDDED=false
      - C2MON_SERVER_ELASTICSEARCH_HOST=es
     volumes:
       - "./c2mon-server/conf/c2mon-server.properties:/c2mon-server/conf/c2mon-server.properties"
     networks:
       - backend
       - frontend
networks:
  backend:
    driver: "bridge"
  frontend:
