apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: c2mon-web
  name: c2mon-web
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: c2mon-web
    spec:
      containers:
      - env:
        - name: C2MON_SERVER_ELASTICSEARCH_HOST
          value: http://es:9200
        - name: C2MON_PORT_61616_TCP
          value: tcp://mq:61616
        - name: C2MON_PORT_9001_TCP_ADDR
          value: c2mon-server
        - name: C2MON_SERVER_JDBC_URL
          value: jdbc:hsqldb:file:///tmp/c2mondb;sql.syntax_ora=true;hsqldb.default_table_type=cached;hsqldb.cache_rows=1000;hsqldb.result_max_memory_rows=2000;hsqldb.cache_size=100
        name: c2mon-web
        image: cern/c2mon-web-ui
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: c2mon-web
  name: c2mon-web
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: c2mon-web