apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    service: es
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: serving
    - port: 9300
      name: node-to-node
  selector:
    io.kompose.service: es
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: es
  name: es-node
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: es
      name: c2mon-es-node
    spec:
      containers:
      - image: cern/c2mon-es
        name: c2mon-es-node
        env:
        - name: namespace
          valueFrom:
           fieldRef:
            fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
           fieldRef:
            fieldPath: metadata.name
        - name: cluster.name
          value: c2mon
        - name: network.host
          value: "0.0.0.0"
        # Required in ES 5.6 images, as they don't pick up ENV config properly
        args: ["-Enode.name=$(node.name)",
               "-Ecluster.name=$(cluster.name)",
               "-Enetwork.host=$(network.host)",
               "-Ediscovery.type=single-node"]
        ports:
        - containerPort: 9200
        - containerPort: 9300
      restartPolicy: Always
status: {}
