apiVersion: v1
kind: Service
metadata:
  namespace: c2mon-dev
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: grafana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: c2mon-dev
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - image: cernoss/c2mon-grafana:1.8.41-SNAPSHOT
        name: grafana
        ports:
        - containerPort: 3000