resources:
  - apachemq.yaml
  - c2mon-server.yaml
  - daq.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: c2mon-server-properties
    envs:
      - c2mon-server.properties
  - name: c2mon-daq-properties
    envs:
      - c2mon-daq.properties