site_name: C2MON
site_url: http://cern.ch/c2mon
docs_dir: ./src
site_dir: ./target

theme: mkdocs

repo_url: https://gitlab.cern.ch/c2mon/c2mon
repo_name: CERN GitLab
edit_uri: blob/master/docs/src/

extra_css:
    - css/extra.css

markdown_extensions:
  - toc:
      permalink: True
  - admonition
